"""empty message

Revision ID: ad43b97b7863
Revises: 22697bb9130f
Create Date: 2022-08-16 09:05:35.484807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad43b97b7863'
down_revision = '22697bb9130f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('portfolio', sa.Column('DailyPnL', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('portfolio', sa.Column('DailyPnLPercentage', sa.Numeric(precision=10, scale=2), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('portfolio', 'DailyPnLPercentage')
    op.drop_column('portfolio', 'DailyPnL')
    # ### end Alembic commands ###
